# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 12:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_order', models.TimeField(auto_now_add=True)),
                ('buy_product', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('byn', models.IntegerField(null=True)),
                ('byr', models.IntegerField(null=True)),
                ('comment', models.CharField(max_length=1000, null=True)),
            ],
        ),
    ]
