# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 18:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='byn',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='byr',
            field=models.IntegerField(default=0),
        ),
    ]
