# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-16 22:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_auto_20160716_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='byn',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='byr',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
